name: Lint and test

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        node-version: [8.13, 10.16, 12.12]

    steps:
      - uses: actions/checkout@v1
      - name: Lint and test with ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm ci, build, lint and test
        run: |
          npm ci
          npm run compile
          npm run lint
          npm test
        env:
          CI: true
